"""initial migration

Revision ID: 35b6cea0040e
Revises: 
Create Date: 2026-06-17 18:02:55.102389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b6cea0040e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cctv_cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rtsp_url', sa.String(length=500), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_online_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cctv_cameras_branch_id'), 'cctv_cameras', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cctv_cameras_company_id'), 'cctv_cameras', ['company_id'], unique=False)
    op.create_table('cctv_company_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('send_low_confidence_to_hrms', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cctv_company_settings_company_id'), 'cctv_company_settings', ['company_id'], unique=True)
    op.create_table('cctv_detection_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('snapshot_url', sa.String(length=500), nullable=True),
    sa.Column('payload_sent', sa.JSON(), nullable=True),
    sa.Column('payload_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_response_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cctv_cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cctv_detection_logs_branch_id'), 'cctv_detection_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cctv_detection_logs_company_id'), 'cctv_detection_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_cctv_detection_logs_employee_id'), 'cctv_detection_logs', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cctv_detection_logs_employee_id'), table_name='cctv_detection_logs')
    op.drop_index(op.f('ix_cctv_detection_logs_company_id'), table_name='cctv_detection_logs')
    op.drop_index(op.f('ix_cctv_detection_logs_branch_id'), table_name='cctv_detection_logs')
    op.drop_table('cctv_detection_logs')
    op.drop_index(op.f('ix_cctv_company_settings_company_id'), table_name='cctv_company_settings')
    op.drop_table('cctv_company_settings')
    op.drop_index(op.f('ix_cctv_cameras_company_id'), table_name='cctv_cameras')
    op.drop_index(op.f('ix_cctv_cameras_branch_id'), table_name='cctv_cameras')
    op.drop_table('cctv_cameras')
    # ### end Alembic commands ###
