"""Refactor IDs to UUID and add companies

Revision ID: 4ac2e3c607ca
Revises: a441e99c6c1c
Create Date: 2026-09-09 16:02:57.924342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac2e3c607ca'
down_revision: Union[str, Sequence[str], None] = 'a441e99c6c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('attendance_cctv', 'id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='id::uuid')
    op.alter_column('attendance_cctv', 'company_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='company_id::uuid')
    op.alter_column('attendance_cctv', 'employee_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='employee_id::uuid')
    op.alter_column('attendance_cctv', 'shift_assignment_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='shift_assignment_id::uuid')
    op.alter_column('attendance_cctv', 'leave_type_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='leave_type_id::uuid')
    op.alter_column('attendance_cctv', 'leave_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='leave_id::uuid')
    op.alter_column('attendance_cctv', 'attendance_request_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='attendance_request_id::uuid')
    op.alter_column('event_visitor_events', 'id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='id::uuid')
    op.alter_column('event_visitor_events', 'session_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='session_id::uuid')
    op.alter_column('event_visitor_sessions', 'id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='id::uuid')
    op.alter_column('event_visitor_sessions', 'event_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='event_id::uuid')
    op.alter_column('events', 'id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='id::uuid')
    op.alter_column('events', 'user_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='user_id::uuid')
    op.alter_column('events', 'company_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='company_id::uuid')
    op.alter_column('users', 'id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using='id::uuid')
    op.alter_column('users', 'company_id',existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using='company_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('events', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('events', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('event_visitor_sessions', 'event_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('event_visitor_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('event_visitor_events', 'session_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('event_visitor_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('attendance_cctv', 'attendance_request_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('attendance_cctv', 'leave_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('attendance_cctv', 'leave_type_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('attendance_cctv', 'shift_assignment_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('attendance_cctv', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('attendance_cctv', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('attendance_cctv', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_table('companies')
    # ### end Alembic commands ###
