"""Add account_type to users

Revision ID: 8b85581ccb78
Revises: 4ac2e3c607ca
Create Date: 2026-09-09 16:44:14.196811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b85581ccb78'
down_revision: Union[str, Sequence[str], None] = '4ac2e3c607ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
