"""Add events table and related columns

Revision ID: f11ea1a7d470
Revises: fe8c9521e850
Create Date: 2026-09-09 12:40:46.133138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f11ea1a7d470'
down_revision: Union[str, Sequence[str], None] = 'fe8c9521e850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_start', sa.String(length=10), nullable=True),
    sa.Column('event_end', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event_visitor_sessions', sa.Column('event_start', sa.String(length=10), nullable=True))
    op.add_column('event_visitor_sessions', sa.Column('event_end', sa.String(length=10), nullable=True))
    op.add_column('event_visitor_sessions', sa.Column('event_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_visitor_sessions', 'event_id')
    op.drop_column('event_visitor_sessions', 'event_end')
    op.drop_column('event_visitor_sessions', 'event_start')
    op.create_table('event_cctv_camera',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('camera_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=10), server_default=sa.text("'in'::character varying"), autoincrement=False, nullable=False),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('people_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('first_detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('client_reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('event_cctv_camera_pkey'))
    )
    op.create_index(op.f('ix_event_cctv_camera_event_type'), 'event_cctv_camera', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_event_date'), 'event_cctv_camera', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_daily_camera_event'), 'event_cctv_camera', ['company_id', 'camera_id', 'event_date', 'event_type'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_company_id'), 'event_cctv_camera', ['company_id'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_client_reference_id'), 'event_cctv_camera', ['client_reference_id'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_camera_id'), 'event_cctv_camera', ['camera_id'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_branch_id'), 'event_cctv_camera', ['branch_id'], unique=False)
    op.create_table('event_cctv_camera_captures',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event_cctv_camera_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('camera_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=10), server_default=sa.text("'in'::character varying"), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('snapshot_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('bbox_x1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bbox_y1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bbox_x2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bbox_y2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('event_cctv_camera_captures_pkey'))
    )
    op.create_index(op.f('ix_event_cctv_camera_captures_event_type'), 'event_cctv_camera_captures', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_captures_event_cctv_camera_id'), 'event_cctv_camera_captures', ['event_cctv_camera_id'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_captures_detected_at'), 'event_cctv_camera_captures', ['detected_at'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_captures_company_id'), 'event_cctv_camera_captures', ['company_id'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_captures_client_reference_id'), 'event_cctv_camera_captures', ['client_reference_id'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_captures_camera_id'), 'event_cctv_camera_captures', ['camera_id'], unique=False)
    op.create_index(op.f('ix_event_cctv_camera_captures_branch_id'), 'event_cctv_camera_captures', ['branch_id'], unique=False)
    op.drop_table('events')
    # ### end Alembic commands ###
