"""Add EventVisitorSession and remove AttendanceCCTV unique constraint

Revision ID: fe8c9521e850
Revises: a7b8c9d0e1f2
Create Date: 2026-09-08 16:15:18.760263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8c9521e850'
down_revision: Union[str, Sequence[str], None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_visitor_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('camera_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('attendance_cctv', 'address_in',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('attendance_cctv', 'address_out',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.execute("ALTER TABLE attendance_cctv DROP CONSTRAINT IF EXISTS uq_attendance_cctv_company_employee_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_attendance_cctv_company_employee_date'), 'attendance_cctv', ['company_id', 'employee_id', 'attendance_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance_cctv', 'address_out',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('attendance_cctv', 'address_in',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('event_visitor_sessions')
    # ### end Alembic commands ###
